name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Prepare Build
        run: echo "Build step - no processing needed"
      - name: Upload Files
        uses: actions/upload-artifact@v3
        with:
          name: site-files
          path: .

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Files
        uses: actions/download-artifact@v3
        with:
          name: site-files
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
