name: DeliveryDeployment

on:
  workflow_run:
    workflows: ["Integration"]
    types:
      - completed
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: website-files
          path: .
      
      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Re-upload do artefato para Deploy
        uses: actions/upload-artifact@v4
        with:
          name: prepared-website
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    environment:
      name: github-pages
    steps:
      - name: Baixar artefato preparado
        uses: actions/download-artifact@v4
        with:
          name: prepared-website
          path: .

      - name: Fazer upload para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v4
