name: Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Upload artefato do site
        uses: actions/upload-artifact@v4
        with:
          name: website-files
          path: .

      - name: Verificar se index.html existe
        run: test -f index.html && echo "index.html encontrado" || exit 1
        
